### ISSUE TITLE
你好，我使用了此库，还是有的framework没被解密

### ISSUE THREAD

**Issue by github410117** [TozyZuo/TZLoadAllLibs#3]
我想砸支付宝的壳，发现有的framework没被解密，然后看到了这个库，我勾选了然后加载然后用frida砸壳，最后也是提示该framework被加密， 是我没成功还是对方有相应措施？特来请教一下
![image](https://user-images.githubusercontent.com/15375736/49656191-a3be2580-fa77-11e8-8a89-9923a9db65f2.png)

**Comment by TozyZuo** [comment]
可否贴下log

**Comment by github410117** [comment]
![image](https://user-images.githubusercontent.com/15375736/49681167-1d85fb80-fad8-11e8-9ff4-8df062fc0b7d.png)
你好，看log是有加载成功，但是导出的ipa放到monkey里运行就提示上面那个了

**Comment by github410117** [comment]
已自己解决！和库无关，感谢！

**Comment by alongmatch** [comment]
你好我也碰到了这个问题是什么原因
